def printgit():
    config='''
# i have removed ignoring dlls but you can reanable it by uncomenting the # 
#
#    
#

## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

###################
# compiled source #
###################
*.com
*.class
#*.dll
*.exe
*.pdb
*.dll.config
*.cache
*.suo
# Include dlls if they’re in the NuGet packages directory
!/packages/*/lib/*.dll
# Include dlls if they're in the CommonReferences directory
!*CommonReferences/*.dll
####################
# VS Upgrade stuff #
####################
_UpgradeReport_Files/
###############
# Directories #
###############
bin/
obj/
TestResults/
###################
# Web publish log #
###################
*.Publish.xml
#############
# Resharper #
#############
/_ReSharper.*
*.ReSharper.*
############
# Packages #
############
# it’s better to unpack these files and commit the raw source
# git has its own built in compression methods
*.7z
*.dmg
*.gz
*.iso
*.jar
*.rar
*.tar
*.zip
######################
# Logs and databases #
######################
*.log
*.sqlite
# OS generated files #
######################
.DS_Store?
ehthumbs.db
Icon?
Thumbs.db


# User-specific files
*.user
*.userosscache
*.sln.docstates

# User-specific files (MonoDevelop/Xamarin Studio)
*.userprefs

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
build/
bld/
[Bb]in/
[Oo]bj/

# Visual Studo 2015 cache/options directory
.vs/

# MSTest test Results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*

# NUNIT
*.VisualState.xml
TestResult.xml

# Build Results of an ATL Project
[Dd]ebugPS/
[Rr]eleasePS/
dlldata.c

# DNX
project.lock.json
artifacts/

*_i.c
*_p.c
*_i.h
*.ilk
*.meta
*.obj
*.pch
*.pgc
*.pgd
*.rsp
*.sbr
*.tlb
*.tli
*.tlh
*.tmp
*.tmp_proj
*.vspscc
*.vssscc
.builds
*.pidb
*.svclog
*.scc

# Chutzpah Test files
_Chutzpah*

# Visual C++ cache files
ipch/
*.aps
*.ncb
*.opensdf
*.sdf
*.cachefile

# Visual Studio profiler
*.psess
*.vsp
*.vspx

# TFS 2012 Local Workspace
$tf/

# Guidance Automation Toolkit
*.gpState

# ReSharper is a .NET coding add-in
_ReSharper*/
*.[Rr]e[Ss]harper
*.DotSettings.user

# JustCode is a .NET coding add-in
.JustCode

# TeamCity is a build add-in
_TeamCity*

# DotCover is a Code Coverage Tool
*.dotCover

# NCrunch
_NCrunch_*
.*crunch*.local.xml

# MightyMoose
*.mm.*
AutoTest.Net/

# Web workbench (sass)
.sass-cache/

# Installshield output folder
[Ee]xpress/

# DocProject is a documentation generator add-in
DocProject/buildhelp/
DocProject/Help/*.HxT
DocProject/Help/*.HxC
DocProject/Help/*.hhc
DocProject/Help/*.hhk
DocProject/Help/*.hhp
DocProject/Help/Html2
DocProject/Help/html

# Click-Once directory
publish/

# Publish Web Output
*.[Pp]ublish.xml
*.azurePubxml
# TODO: Comment the next line if you want to checkin your web deploy settings 
# but database connection strings (with potential passwords) will be unencrypted
*.pubxml
*.publishproj

# NuGet Packages
*.nupkg
# The packages folder can be ignored because of Package Restore
**/packages/*
# except build/, which is used as an MSBuild target.
!**/packages/build/
# Uncomment if necessary however generally it will be regenerated when needed
#!**/packages/repositories.config

# Windows Azure Build Output
csx/
*.build.csdef

# Windows Store app package directory
AppPackages/

# Visual Studio cache files
# files ending in .cache can be ignored
*.[Cc]ache
# but keep track of directories ending in .cache
!*.[Cc]ache/

# Others
ClientBin/
[Ss]tyle[Cc]op.*
~$*
*~
*.dbmdl
*.dbproj.schemaview
*.pfx
*.publishsettings
node_modules/
bower_components/
orleans.codegen.cs

# RIA/Silverlight projects
Generated_Code/

# Backup & report files from converting an old project file
# to a newer Visual Studio version. Backup files are not needed,
# because we have git ;-)
_UpgradeReport_Files/
Backup*/
UpgradeLog*.XML
UpgradeLog*.htm

# SQL Server files
*.mdf
*.ldf

# Business Intelligence projects
*.rdl.data
*.bim.layout
*.bim_*.settings

# Microsoft Fakes
FakesAssemblies/

# Node.js Tools for Visual Studio
.ntvs_analysis.dat

# Visual Studio 6 build log
*.plg

# Visual Studio 6 workspace options file
*.opt



    '''
    return config







def createclass(classfile):
    fin = f'''
    using DevExpress.Data.Filtering;
    using DevExpress.ExpressApp;
    using DevExpress.ExpressApp.DC;
    using DevExpress.ExpressApp.Model;
    using DevExpress.Persistent.Base;
    using DevExpress.Persistent.BaseImpl;
    using DevExpress.Persistent.Validation;
    using DevExpress.Xpo;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.Text;

    namespace {classfile}.Module.BusinessObjects
    {{
        [DefaultClassOptions]
        //[ImageName("BO_Contact")]
        //[DefaultProperty("DisplayMemberNameForLookupEditorsOfThisType")]
        //[DefaultListViewOptions(MasterDetailMode.ListViewOnly, false, NewItemRowPosition.None)]
        //[Persistent("DatabaseTableName")]
        // Specify more UI options using a declarative approach (https://documentation.devexpress.com/#eXpressAppFramework/CustomDocument112701).
        public class CommonClasses : XPLiteObject
        {{ // Inherit from a different class to provide a custom primary key, concurrency and deletion behavior, etc. (https://documentation.devexpress.com/eXpressAppFramework/CustomDocument113146.aspx).
            // Use CodeRush to create XPO classes and properties with a few keystrokes.
            // https://docs.devexpress.com/CodeRushForRoslyn/118557
            public CommonClasses(Session session)
                : base(session)
            {{
            }}

            private string _created_by;
            [XafDisplayName("Created By")]
            [ModelDefault("AllowEdit", "false")]
            //[VisibleInDetailView(false)]
            [VisibleInListView(false)]
            [VisibleInLookupListView(false)]
            public string created_by
            {{
                get {{ return _created_by; }}
                set {{ SetPropertyValue<string>(nameof(created_by), ref _created_by, value); }}
            }}
            private DateTime _created_on;
            [XafDisplayName("Created On")]
            [ModelDefault("AllowEdit", "false")]
            [ModelDefault("DisplayFormat", "{{0: dd-MMM-yyyy}}")]
            [ModelDefault("EditMask", "dd-MMM-yyyy")]
            //[VisibleInDetailView(false)]
            [VisibleInListView(false)]
            [VisibleInLookupListView(false)]
            public DateTime created_on
            {{
                get {{ return _created_on; }}
                set {{ SetPropertyValue<DateTime>(nameof(created_on), ref _created_on, value); }}
            }}
            private string _altered_by;
            [XafDisplayName("Altered By")]
            [ModelDefault("AllowEdit", "false")]
            //[VisibleInDetailView(false)]
            [VisibleInListView(false)]
            [VisibleInLookupListView(false)]
            public string altered_by
            {{
                get {{ return _altered_by; }}
                set {{ SetPropertyValue<string>(nameof(altered_by), ref _altered_by, value); }}
            }}
            private DateTime _date_altered;
            [XafDisplayName("Altered On")]
            [ModelDefault("AllowEdit", "false")]
            [ModelDefault("DisplayFormat", "{{0: dd-MMM-yyyy}}")]
            [ModelDefault("EditMask", "dd-MMM-yyyy")]
            //[VisibleInDetailView(false)]
            [VisibleInListView(false)]
            [VisibleInLookupListView(false)]
            public DateTime date_altered
            {{
                get {{ return _date_altered; }}
                set {{ SetPropertyValue<DateTime>(nameof(date_altered), ref _date_altered, value); }}
            }}

            protected override void OnSaving()
            {{
                base.OnSaving();

                if (Session.IsNewObject(this))
                {{
                    created_by = SecuritySystem.CurrentUserName;
                    created_on = DateTime.Now;
                }}
                else
                {{
                    date_altered = DateTime.Now;
                    altered_by = SecuritySystem.CurrentUserName;
                }}

        
            }}

            public override void AfterConstruction()
            {{
                base.AfterConstruction();
                // Place your initialization code here (https://documentation.devexpress.com/eXpressAppFramework/CustomDocument112834.aspx).
            }}

        }}
    }}
    '''
    return fin

